### ISSUE TITLE
Exception when no server address is set

### ISSUE THREAD

**Issue by hifiberry** [hifiberry/snapcastmpris#3]
If no server address is set and no snapcast server is available, the RCP communication fails with an exception

Nov 29 09:15:21 penta-wohnzimmer python3[1253]: During handling of the above exception, another exception occurred:
Nov 29 09:15:21 penta-wohnzimmer python3[1253]: Traceback (most recent call last):
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 446, in increment
Nov 29 09:15:21 penta-wohnzimmer python3[1253]: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=1780): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x748fdc28>: Failed to establish a new connection: [Errno 111] Connection refused'))
Nov 29 09:15:21 penta-wohnzimmer python3[1253]: During handling of the above exception, another exception occurred:
Nov 29 09:15:21 penta-wohnzimmer python3[1253]: Traceback (most recent call last):
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/opt/snapcastmpris/snapcastmpris.py", line 123, in <module>
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:     snapcast_wrapper = SnapcastWrapper(glib_main_loop, server_address)
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/opt/snapcastmpris/SnapcastWrapper.py", line 28, in __init__
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:     self.rpc_wrapper = SnapcastRpcWrapper(server_address)
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/opt/snapcastmpris/SnapcastRpcWrapper.py", line 27, in __init__
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:     self.verify_srver_rpc_version()
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/opt/snapcastmpris/SnapcastRpcWrapper.py", line 107, in verify_srver_rpc_version
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:     result = self.call_snapserver_jsonrcp(payload)
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/opt/snapcastmpris/SnapcastRpcWrapper.py", line 117, in call_snapserver_jsonrcp
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:     response = requests.post('http://' + self.server_address + ":1780/jsonrpc", json=payload_data)
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/usr/lib/python3.9/site-packages/requests/api.py", line 119, in post
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
Nov 29 09:15:21 penta-wohnzimmer python3[1253]:   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
Nov 29 09:15:21 penta-wohnzimmer python3[1253]: requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=1780): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x748fdc28>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Bertware** [comment]
I've seen this one locally on my "real" system as well, will look into it. Seems like it fails to obtain the IP address through zeroconf, although (in my case) this worked perfectly on my test system with the same network environment and snapcast server, so will have to debug as to why it won't connect now.

**Comment by Bertware** [comment]
I just tried a couple of times, but can't reproduce it anymore. It seems to require a really specific set of circumstances to trigger. Do you have the earlier logs of the fragment you posted? You can filter on the python process (1253)
Either one of these lines should be posted, or an exception:

`logging.error("Failed to obtain snapserver address through zeroconf!")`
`logging.info("Obtained snapserver address through zeroconf: " + address)`

I'll reinstall my test environment tonight to see if the reinstall can reproduce it.

**Comment by hifiberry** [comment]
Nov 30 08:42:34 amp100 python3[1768]: INFO: root - MAC address for interface dummy0: 1a:e5:96:a6:32:f1
Nov 30 08:42:34 amp100 python3[1768]: Traceback (most recent call last):
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 84, in create_connection
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 74, in create_connection
Nov 30 08:42:34 amp100 python3[1768]: ConnectionRefusedError: [Errno 111] Connection refused
Nov 30 08:42:34 amp100 python3[1768]: During handling of the above exception, another exception occurred:
Nov 30 08:42:34 amp100 python3[1768]: Traceback (most recent call last):
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/http/client.py", line 1255, in request
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/http/client.py", line 950, in send
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 187, in connect
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
Nov 30 08:42:34 amp100 python3[1768]: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x748a4c28>: Failed to establish a new connection: [Errno 111] Connection refused
Nov 30 08:42:34 amp100 python3[1768]: During handling of the above exception, another exception occurred:
Nov 30 08:42:34 amp100 python3[1768]: Traceback (most recent call last):
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 446, in increment
Nov 30 08:42:34 amp100 python3[1768]: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=1780): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x748a4c28>: Failed to establish a new connection: [Errno 111] Connection refused'))
Nov 30 08:42:34 amp100 python3[1768]: During handling of the above exception, another exception occurred:
Nov 30 08:42:34 amp100 python3[1768]: Traceback (most recent call last):
Nov 30 08:42:34 amp100 python3[1768]:   File "/opt/snapcastmpris/snapcastmpris.py", line 123, in <module>
Nov 30 08:42:34 amp100 python3[1768]:     snapcast_wrapper = SnapcastWrapper(glib_main_loop, server_address)
Nov 30 08:42:34 amp100 python3[1768]:   File "/opt/snapcastmpris/SnapcastWrapper.py", line 28, in __init__
Nov 30 08:42:34 amp100 python3[1768]:     self.rpc_wrapper = SnapcastRpcWrapper(server_address)
Nov 30 08:42:34 amp100 python3[1768]:   File "/opt/snapcastmpris/SnapcastRpcWrapper.py", line 27, in __init__
Nov 30 08:42:34 amp100 python3[1768]:     self.verify_srver_rpc_version()
Nov 30 08:42:34 amp100 python3[1768]:   File "/opt/snapcastmpris/SnapcastRpcWrapper.py", line 107, in verify_srver_rpc_version
Nov 30 08:42:34 amp100 python3[1768]:     result = self.call_snapserver_jsonrcp(payload)
Nov 30 08:42:34 amp100 python3[1768]:   File "/opt/snapcastmpris/SnapcastRpcWrapper.py", line 117, in call_snapserver_jsonrcp
Nov 30 08:42:34 amp100 python3[1768]:     response = requests.post('http://' + self.server_address + ":1780/jsonrpc", json=payload_data)
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/requests/api.py", line 119, in post
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
Nov 30 08:42:34 amp100 python3[1768]:   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
Nov 30 08:42:34 amp100 python3[1768]: requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=1780): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x748a4c28>: Failed to establish a new connection: [Errno 111] Connection refused'))
Nov 30 08:42:34 amp100 systemd[1]: snapcastmpris.service: Main process exited, code=exited, status=1/FAILURE

**Comment by Bertware** [comment]
While not a direct cause, I'm interested in the network setup: 
` INFO: root - MAC address for interface dummy0: 1a:e5:96:a6:32:f1`
Is dummy0 a "real" network connection with connectivity? Is this the AP used for setup?

If it is your own device, could you either run in verbose mode, or add a logging line `logging.info(service_info)` at snapcastmpris.py:76 and report the output?
The resulting code would look like this:
```
    service_info = zerocfg.get_service_info("_snapcast._tcp.local.", "Snapcast._snapcast._tcp.local.", 3000)
    logging.info(service_info)
    if service_info is None:
```

**Edit:** Is the real address an IPv4 or IPv6 address?
